terraform {
  required_version = ">= 1.11"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
  }

  # Partial backend configuration: bucket and region come from backend.hcl
  # (generated by ../../bootstrap), because the bucket name contains the
  # sandbox account ID and changes every session.
  #
  #   terraform init -backend-config=backend.hcl
  backend "s3" {
    key          = "dev/terraform.tfstate"
    encrypt      = true
    use_lockfile = true # native S3 state locking - no DynamoDB table needed
  }
}
